name: Supabase Keep-Alive

on:
  schedule:
    - cron: '0 9 * * 1,4'  # 毎週月曜・木曜の午前9時（UTC）
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Supabase Client
        run: npm install @supabase/supabase-js

      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          node -e "
          const { createClient } = require('@supabase/supabase-js');
          const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);
          supabase.from('reservations').select('id').limit(1).then(result => {
            console.log('Supabase ping successful:', result);
            process.exit(0);
          }).catch(error => {
            console.error('Supabase ping failed:', error);
            process.exit(1);
          });
          "